#!/usr/bin/perl -w

use v5.22.2;
use strict;

use File::Find;

my $param1 = shift @ARGV;
my $param2 = shift @ARGV;

if($param2 eq "-d"){
    my $param3 = shift @ARGV;
    find(sub {say if -d && $_ =~ /$param3/}, $param1);
}
else{
  my $ch = substr $param2, 0, 1;

  $ch eq "." ?
      find(sub {say if -f && $_ =~ /$param2$/}, $param2)
      :
      find(sub {say if -f && $_ =~ /$param2/}, $param1);
}
